### ISSUE TITLE
启用使用 ffmpeg 转码音频下载文件就会闪退

### ISSUE THREAD

**Issue by Yuuki-Rin** [HIM049/BADownloaderUI#23]
启用使用 ffmpeg 转码音频下载文件就会闪退
版本4.5

**Comment by HIM049** [comment]
我自己测试的时候貌似没有遇到类似问题，请问系统内有安装FFmpeg与对应的环境变量吗，可以测试一下系统内FFmpeg能否正常使用。

**Comment by Yuuki-Rin** [comment]
> 我自己测试的时候貌似没有遇到类似问题，请问系统内有安装FFmpeg与对应的环境变量吗，可以测试一下系统内FFmpeg能否正常使用。

设置的系统环境变量 没重启生效
