### ISSUE TITLE
下载的音频文件,没有扩展名

### ISSUE THREAD

**Issue by nixingshiguang** [HIM049/BADownloaderUI#26]
如下图所示,所有文件都没有文件扩展名,请问能否手动加上,应该加什么扩展名?wav/mp3
![image](https://github.com/user-attachments/assets/47800883-6bd5-4f4f-ac82-70d2490c8311)

**Comment by HIM049** [comment]
该问题是因为默认生成的设置中使用了错误的缺少了文件后缀占位符的文件名模板。该问题已在 7e78666 中修复
