### ISSUE TITLE
scoop install

### ISSUE THREAD

**Issue by Weidows** [HIM049/BADownloaderUI#7]
https://github.com/Weidows-projects/scoop-3rd/blob/main/bucket/BADownloaderUI.json

加到了我的软件库, 已经收录到了整合库, 方便安装升级

    scoop bucket add apps https://github.com/kkzzhizhou/scoop-apps
    scoop install BADownloaderUI

**Comment by HIM049** [comment]
收到，下个版本会添加到 README 中，感谢支持

**Comment by HIM049** [comment]
已在 48155c6 中完成。
